import Navbar from "./Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <Navbar />
        <body>{children}</body>
    </html>
  )
}